### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by ghost** [andr9528/ComputerScienceFinalProject#17]
Use cases

**Comment by ghost** [comment]
Written. Needs approval.

**Comment by Kristiansax** [comment]
Is this only headlines for the use cases? There are three types of use cases: Brief, casual and fully dressed. These barely pass as brief, but I would suggest we make them casual cases with a main success scenario and alternate flows.

**Comment by ghost** [comment]
Exapanded use cases from brief to casual.
