### ISSUE TITLE
Role Descriptions

### ISSUE THREAD

**Issue by ghost** [andr9528/ComputerScienceFinalProject#21]
A description of the different roles of the group's members.

**Comment by ghost** [comment]
Added role descriptions document as I imagine the project running forward. Will need to be comfirmed by all members.

**Comment by andr9528** [comment]
See inputs made on discord, between 11:40-12:00 on 15-11-2018

**Comment by ghost** [comment]
Reopened due to group feedback.

**Comment by ghost** [comment]
I have updated the Role Descriptions with the suggestions from the Discord chat mentioned ealier. Also clarified what the implications of the role definitions means.
