### ISSUE TITLE
Flow chart of how client should work

### ISSUE THREAD

**Issue by andr9528** [andr9528/ComputerScienceFinalProject#22]
Create a flow chart of how the client console should function

**Comment by andr9528** [comment]
Scroll down in the file 'Console Work Flow'

**Comment by andr9528** [comment]
Reopening, because of failure to indicate that the client cease to run, in the event that no ads have been assigned to it.

**Comment by ghost** [comment]
Moved the condition statements from statement boxes to the condition boxes. Otherwise it looks good.
