### ISSUE TITLE
Domain Model

### ISSUE THREAD

**Issue by Kristiansax** [andr9528/ComputerScienceFinalProject#31]

**Comment by Kristiansax** [comment]
Created and added to documentation

**Comment by ghost** [comment]
Jeg tænkte lige på, at en reklame nok skal have en ejer, ie. kunden. Desuden skal en skærm nok have en placering, eller lignende. 
Derudover vil jeg også meget gerne høre @andr9528 tanker omkring domænemodellen.

**Comment by Kristiansax** [comment]
Made changes to be more in line with Larman
