### ISSUE TITLE
Business Case

### ISSUE THREAD

**Issue by ghost** [andr9528/ComputerScienceFinalProject#37]
- [x] Passer resultaterne fra business casen overens med hvad der er beskrevet i modellen? (Rød tråd!)
- [x] Er alle vigtige parthavere nævnt og beskrevet?
- [x] Er løsningen passende beskrevet, samt alternative løsninger og hvorfor vi har valgt ikke at gå videre med dem?

**Comment by ghost** [comment]
Business Case first udkast. Please take a look and give suggestions.

**Comment by ghost** [comment]
Gotten feedback to finish.

**Comment by ghost** [comment]
Still missing an alternative solution and KPI's. Might need help with these.

**Comment by andr9528** [comment]
Linje 2:
I oktober stiftede vi for første gang **kontakt** med OneHouse **hvor vi fik overrakt** ~~og~~ deres problemstilling, da den administrerende direktør Lars Thomsen delte deres projektbeskrivelse med os.
- Tilføjet et komma før 'da'

Linje 4:
Der~~med~~**for** bør løsningen være i stand til at understøtte denne model, ~~Der er både~~ **ved at skabe** mulighed**en** for at sælge selve systemet til kunder ~~og~~ **eller** at sælge servicen systemet giver, ~~V~~vi anbefaler **dog den sidste mulighed** ~~det sidste~~, da ~~dette også~~ **den** vil hjælpe OneHouse på længere sigt.
- Ændret punktum efter 'model' til et komma
- Ændret punktum efter 'giver' til et komma

**Comment by ghost** [comment]
Used the suggestions from André in the Business Case.
