### ISSUE TITLE
Business Model

### ISSUE THREAD

**Issue by ghost** [andr9528/ComputerScienceFinalProject#38]
- [x] Giver forretningsmodellen et tilfredstillende overblik over virksomheden og dens forretningsgrundlag?
- [x] Er alle vigtige intægter og udgifter taget i betragtning?
- [x] Er alle vigtige partnere, aktiviteter og ressourcer beskrevet?

**Comment by chri894u** [comment]
- [ ] Key Partners
- [ ] Key Activities
- [ ] Key Resources
- [ ] Customer Segments
- [ ] Customer Relationships
- [ ] Channels
- [ ] Value Proposition
- [ ] Cost Structure
- [ ] Revenue Streams

**Comment by ghost** [comment]
Business Model first udkast. Please take a look and give suggestions.

**Comment by ghost** [comment]
Gotten feedback to finish.

**Comment by ghost** [comment]
Finished.

**Comment by andr9528** [comment]
Linje 9:
Derudover har OneHouse også engangskunder, ~~Disse kommer~~ **som** for det meste **kommer** for **at få** rådgivning eller softwareudvikling.
- Ændret punktum i overstående stykke til komma.
- 3-4 relativ korte sætninger starter med 'Onehouse' skal måske omskrives lidt.

Linje 11:
Da OneHouse er afhængige af deres faste kunder ... Især de faste kunder er vigtige for OneHouse.
 - Unødvendig gentagelse?

Generalt
- Mangler kommaer her og der, som vi kan fikse når den kommer over i rapporten

**Comment by ghost** [comment]
Used the suggestions from André in the Business Model.
