### ISSUE TITLE
(15/15) Cleanwriting/Rewriting System Development section for Overleaf

### ISSUE THREAD

**Issue by Kristiansax** [andr9528/ComputerScienceFinalProject#42]
- [x] Proper grammar
- [x] Proper spelling
- [x] Contains everything needed
- [x] Red thread
- [x] No contradictions
- [x] Pertains to the learning goals

**Comment by Kristiansax** [comment]
Has been updated, but needs more information about why we picked the method we did, as well as footnotes

**Comment by Kristiansax** [comment]
Section is done, some things need to be agreed upon with the group. Footnotes will be done as a seperate task.

**Comment by andr9528** [comment]
5.3.3
Christian står for hjemme siden ja, men indtil videre er det mig der har lavet web servicen.
Ligner at Christian lavet meget lidt, når han kun har en rolle. måske en rolle kunne blive tilføjet med relevans til business?

5.1, 5.5
Tekst i parentes, skal enten, beholdes, omskrives eller slettes, ser ikke pænt ud med med hele sætninger i parentes.

Der var også nogle få stave fejl her og der, som jeg har rettet, samt nogle få manglende kommaer, som jeg også rettet.

Ser godt ud på nær de steder, nævnt ovenover.

**Comment by Kristiansax** [comment]
5.3.3: fixed, changed Christians roles and added another one.

5.1, 5.5: Removed parenthesis and some of the text

Added paragraph 5.2.1.3 about features on the SCRUM board

**Comment by andr9528** [comment]
Har lige kigget de seneste ændringer igennem, og det ser fint ud.
