### ISSUE TITLE
(5/5) Create new display unit on setup

### ISSUE THREAD

**Issue by andr9528** [andr9528/ComputerScienceFinalProject#45]
- [ ] Single Responsibility principle
- [ ] Open/Close principle
- [ ] Liskov's substitution principle
- [ ] Interface segregation principle
- [ ] Dependency inversion principle

Will be done in branch called 'ClientSprintOne'

Task:
- [x] Created SD over the Initialization of the display unit.
- [x] Create Method Prologs over the Initialization method.
- [x] Code the Initialization of the display unit.
- [ ] Test if the Initialization works as expected.

**Comment by andr9528** [comment]
Client will succesfully create itself in the database on first run.

**Comment by Kristiansax** [comment]
Shares the same issues as #46
