### ISSUE TITLE
(5/5) Find itself in the database

### ISSUE THREAD

**Issue by andr9528** [andr9528/ComputerScienceFinalProject#46]
- [ ] Single Responsibility principle
- [ ] Open/Close principle
- [ ] Liskov's substitution principle
- [ ] Interface segregation principle
- [ ] Dependency inversion principle

Will be done in branch called 'ClientSprintOne'

Task:
- [x] Created SD over the ability to find itself in the database.
- [x] Create Method Prologs over the Find itself method.
- [x] Code the Find Itself functionality.
- [ ] Test if it can find itself in the database.

**Comment by andr9528** [comment]
Client can succesfully find itself in the database and retrive itself for future use

**Comment by Kristiansax** [comment]
- [x] Method prologues missing input and output. 
- [x] 'Find Display Unit' SD missing a return from ReadKeyInfo().
- [x] SD lifelines (the dotted downwards lines) needs to extend to the bottom of the model.
- [x] Init method prologue missing exception.
- [x] 'Initialize display unit' SD needs updating.
- [x] 'Run Display Unit' SD needs updating after new information.
- [x] 'GetHostName' method prologue possibly missing assumption.
- [x] 'Download' method prologue needs to be renamed to DownloadFileFromRemoteLocation to reflect the programs naming of the method.
